steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=${_TARGET_GCR}/${_TARGET_PROJECT}/cloud-builders/terraform'
      - '--build-arg=TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
      - '--build-arg=TERRAFORM_SHA256SUM=${_TERRAFORM_SHA256SUM}'
      - '--build-arg=CLOUDSDK_VERSION=${_CLOUDSDK_VERSION}'
      - '--build-arg=TERRAFORM_GOOGLE_PROVIDER_VERSION=${_TERRAFORM_GOOGLE_PROVIDER_VERSION}'
      - '--build-arg=TERRAFORM_GOOGLE_PROVIDER_SHA256SUM=${_TERRAFORM_GOOGLE_PROVIDER_SHA256SUM}'
      - '--build-arg=TERRAFORM_GOOGLE_BETA_PROVIDER_VERSION=${_TERRAFORM_GOOGLE_BETA_PROVIDER_VERSION}'
      - '--build-arg=TERRAFORM_GOOGLE_BETA_PROVIDER_SHA256SUM=${_TERRAFORM_GOOGLE_BETA_PROVIDER_SHA256SUM}'
      - '--build-arg=TERRAFORM_GSUITE_PROVIDER_VERSION=${_TERRAFORM_GSUITE_PROVIDER_VERSION}'
      - '--build-arg=TERRAFORM_GSUITE_PROVIDER_SHA256SUM=${_TERRAFORM_GSUITE_PROVIDER_SHA256SUM}'
      - '--build-arg=TERRAFORM_EXTERNAL_PROVIDER_VERSION=${_TERRAFORM_EXTERNAL_PROVIDER_VERSION}'
      - '--build-arg=TERRAFORM_EXTERNAL_PROVIDER_SHA256SUM=${_TERRAFORM_EXTERNAL_PROVIDER_SHA256SUM}'
      - '--build-arg=TERRAFORM_RANDOM_PROVIDER_VERSION=${_TERRAFORM_RANDOM_PROVIDER_VERSION}'
      - '--build-arg=TERRAFORM_RANDOM_PROVIDER_SHA256SUM=${_TERRAFORM_RANDOM_PROVIDER_SHA256SUM}'
      - '--build-arg=TERRAFORM_NULL_PROVIDER_VERSION=${_TERRAFORM_NULL_PROVIDER_VERSION}'
      - '--build-arg=TERRAFORM_NULL_PROVIDER_SHA256SUM=${_TERRAFORM_NULL_PROVIDER_SHA256SUM}'
      - '.'
images:
  - '${_TARGET_GCR}/${_TARGET_PROJECT}/cloud-builders/terraform'

substitutions:
  _TARGET_GCR: 'gcr.io'
  _TARGET_PROJECT: 'project'
  _TERRAFORM_VERSION: '0.11.13'
  _TERRAFORM_SHA256SUM: '5925cd4d81e7d8f42a0054df2aafd66e2ab7408dbed2bd748f0022cfe592f8d2'
  _CLOUDSDK_VERSION: '239.0.0'
  _TERRAFORM_GOOGLE_PROVIDER_VERSION: '2.2.0'
  _TERRAFORM_GOOGLE_PROVIDER_SHA256SUM: '90b120ce74f63b36a12a2e078af9a4fb128b29287f6fb1c24f7bb0fe621a86d5'
  _TERRAFORM_GOOGLE_BETA_PROVIDER_VERSION: '2.2.0'
  _TERRAFORM_GOOGLE_BETA_PROVIDER_SHA256SUM: '911fc796ec498b32212417fb10c4473935ae11fcd3e76e840a6c816918c76f61'
  _TERRAFORM_GSUITE_PROVIDER_VERSION: '0.1.17'
  _TERRAFORM_GSUITE_PROVIDER_SHA256SUM: 'e0c87a4279dfcf14688328a6944b64eaca7dcfbe5f4181a549eaa1c1fa413e27'
  _TERRAFORM_EXTERNAL_PROVIDER_VERSION: '1.1.0'
  _TERRAFORM_EXTERNAL_PROVIDER_SHA256SUM: '9719eacc6eec46e8e6636e8881fd8e8762c9592cd47fec58c4d4d8f3feb1b1bf'
  _TERRAFORM_RANDOM_PROVIDER_VERSION: '2.1.0'
  _TERRAFORM_RANDOM_PROVIDER_SHA256SUM: 'f91a82b190e853f032ad5e18cdf625da5ddfa5f0b72d7e39f1875d927a5b2b0d'
  _TERRAFORM_NULL_PROVIDER_VERSION: '2.1.0'
  _TERRAFORM_NULL_PROVIDER_SHA256SUM: 'b27db66404ea0704fb076ef26bb5b5c556a31b81a8b2302ec705a7e46d93d3e0'
